<?php
/** @var \MageSuite\QuickReorder\ViewModel\LatestProductsPurchased $viewModel */
$viewModel = $block->getViewModel();
$headlineText = $block->getHeadlineText();
?>
<?php if ($viewModel->isEnabled() && ($products = $viewModel->getProducts())) : ?>
    <?php
    $jsSettings = json_encode($block->getVar('product_carousel/js') ?: '{}');
    ?>
    <?= /* @noEscape */ $block->getCssOnce('css/products-carousel.css'); ?>
    <div class="cs-container cs-container--latest-purchased-products cs-latest-purchased-products">
        <div class="cs-headline">
            <h3 class="cs-headline__title"><?= /* @noEscape */ $headlineText ?></h3>
        </div>
        <div class="cs-container cs-container--products-carousel">
            <div class="cs-container__inner">
                <div class="cs-products-carousel" data-view-mode="grid"
                     data-mage-init='{"ccProductsCarousel": <?= /* @noEscape */ $jsSettings ?> }'>
                    <div class="cs-products-carousel__carousel">
                        <div class="cs-products-carousel__wrapper">
                            <ul class="cs-products-carousel__slides">
                                <?php foreach ($products as $product) : ?>
                                    <li class="cs-products-carousel__slide">
                                        <?= /* @noEscape */ $block->getLayout()
                                            ->createBlock(\MageSuite\ProductTile\Block\Tile::class)
                                            ->setAreas(['latest_products_purchased'])
                                            ->setSection('latest_products_purchased')
                                            ->setViewMode('grid')
                                            ->render($product);
                                        ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                        <button
                            class="cs-products-carousel__nav cs-products-carousel__nav--prev"
                            type="button">
                            <?= /* @noEscape */ $block->getLayout()
                                ->createBlock(\MageSuite\ThemeHelpers\Block\Icon::class)
                                ->setIconUrl($block->getVar('product_carousel/navigation/arrows/prev/path'))
                                ->setCssClass("cs-products-carousel__nav-icon")
                                ->setAltText(__("Previous"))
                                ->setInlined(true)
                                ->toHtml();
                            ?>
                        </button>
                        <button
                            class="cs-products-carousel__nav cs-products-carousel__nav--next"
                            type="button">
                            <?= /* @noEscape */ $block->getLayout()
                                ->createBlock(\MageSuite\ThemeHelpers\Block\Icon::class)
                                ->setIconUrl($block->getVar('product_carousel/navigation/arrows/next/path'))
                                ->setCssClass("cs-products-carousel__nav-icon")
                                ->setAltText(__("Next"))
                                ->setInlined(true)
                                ->toHtml();
                            ?>
                        </button>
                        <ul class="cs-products-carousel__pagination"></ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
